### ISSUE TITLE
Wiki?

### ISSUE THREAD

**Issue by matteo-tonini** [sparkDEMAND/atom-toolbar-preferred#4]
Hi, 

in README file there's a link to the wiki 
that is suppose to bring me to more examples of config file.
The link doesn't seem to work though.

Would be very useful to have more examples.

Thanks

**Comment by jschwrtz** [comment]
Hi,

My apologies. I just added in a sample config file [here](https://github.com/sparkDEMAND/atom-toolbar-preferred/wiki/Sample-Config) for reference.
